// Emit docs/DRAFT-FIELDS.md from projects.ts.
//
// Generated, not hand-written: a hand-maintained list of unfilled fields drifts
// the moment one is filled, and then it is worse than no list at all.
//
//   node scripts/draft-fields.mjs

import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "src", "content", "projects.ts");

const src = await readFile(SRC, "utf8");

// Walk the file linearly, tracking which project block each DRAFT sits in.
// Parsing TypeScript properly would need a compiler pass for no extra accuracy
// here: slug and title are one-per-block string literals in a fixed order.
const lines = src.split(/\r?\n/);
const groups = [];
let current = null;

for (let i = 0; i < lines.length; i++) {
  const line = lines[i];

  const slug = line.match(/^\s*slug:\s*'([^']+)'/);
  if (slug) {
    current = { slug: slug[1], title: slug[1], drafts: [] };
    groups.push(current);
    continue;
  }

  const title = line.match(/^\s*title:\s*'([^']+)'/);
  if (title && current && current.title === current.slug) {
    current.title = title[1];
    continue;
  }

  const draft = line.match(/DRAFT:\s*(.*)$/);
  if (draft && current) {
    current.drafts.push({
      line: i + 1,
      text: draft[1].replace(/',?\s*\]?,?\s*$/, "").trim(),
    });
  }
}

const withDrafts = groups.filter((g) => g.drafts.length > 0);
const total = withDrafts.reduce((n, g) => n + g.drafts.length, 0);

const out = [
  "# DRAFT fields",
  "",
  `Generated by \`node scripts/draft-fields.mjs\` — do not edit by hand.`,
  "",
  `**${total} unfilled** across ${withDrafts.length} of ${groups.length} projects.`,
  "",
  "These are the `limitations` entries only Hamza can write. They are stripped",
  "from the rendered case study (`src/app/work/[slug]/page.tsx`) and shown as a",
  "dev-only banner, so nothing below is currently public.",
  "",
  "Why they matter: the limitations block is the highest-signal section on a case",
  "study for a senior reviewer. An empty one reads as inexperience, and a vague",
  "one reads as evasion. Specific and technical is the bar — lighting, fabric,",
  "occlusion, pose, drift, throughput ceiling.",
  "",
  "---",
  "",
];

for (const g of withDrafts) {
  out.push(`## ${g.title}`);
  out.push("");
  out.push(`\`${g.slug}\` — ${g.drafts.length} unfilled`);
  out.push("");
  for (const d of g.drafts) {
    out.push(`- [ ] **projects.ts:${d.line}** — ${d.text}`);
  }
  out.push("");
}

await mkdir(path.join(ROOT, "docs"), { recursive: true });
await writeFile(path.join(ROOT, "docs", "DRAFT-FIELDS.md"), out.join("\n"));
console.log(`docs/DRAFT-FIELDS.md — ${total} drafts across ${withDrafts.length} projects`);
